### ISSUE TITLE
Support extended metadata recently added to accounts-sandstorm

### ISSUE THREAD

**Issue by kentonv** [jacksingleton/accounts-sandstorm-dev#1]
Hi Jack,

I updated accounts-sandstorm to support the new Sandstorm profile metadata like avatars. Probably should update accounts-sandstorm-dev too:

https://github.com/sandstorm-io/meteor-accounts-sandstorm/commit/19a6fde497c7b0c67cf46aa5f0382cee9e1323ed

**Comment by jacksingleton** [comment]
Done, thanks for the heads up
