### ISSUE TITLE
ENV variables don't seem to work.

### ISSUE THREAD

**Issue by rchrd2** [jacksingleton/accounts-sandstorm-dev#3]
I run this to start my app:

```
export STUB_PERMISSIONS=modify
meteor
```

Then in my app:

```
console.log(user.services.sandstorm.permissions);
...
> ["owner"] (1)
```

Not sure where in the signal chain this breaks. Could be in this library or the one Kenton wrote... Or I could be doing something wrong.

**Comment by jacksingleton** [comment]
Ah you probably need to clear the local storage in your browser

We added this to the sandforms docs, it should be in this project as well

**Comment by jacksingleton** [comment]
Did that work?

**Comment by rchrd2** [comment]
Just tried clearing local storage, and YES, that worked.

For what it's worth, it would be nice if it updated without having to clear localstorage. I think that's out of the scope of this library.

Thanks.
